<div class="thumbnail">
  <div class="row">
    <div class="col-md-4">
      <div class="container">
        <h2>Activiteiten in jouw buurt</h2>
        <p class="lead visible-lg visible-md">Kom uit uw kot en zoek een activiteit in jouw buurt:</p>
        <form role="form">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Postcode of gemeente"></input>
            <span class="input-group-btn"><button type="submit" class="btn btn-warning">Zoek</button></span>
          </div>
        </form>
      </div>
    </div>
    <div class="col-md-8">
      <img src="http://placehold.it/773x338" class="img-responsive hidden-xs hidden-sm" />
    </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-sm-4">
    <div class="thumbnail text-center">
      <span class="fa-stack fa-5x">
        <i class="fa fa-circle fa-stack-2x text-muted"></i>
        <i class="fa fa-lightbulb-o fa-stack-1x fa-inverse"></i>
      </span>
      <div class="caption">
        <h3>Tips</h3>
        <p>Start to Swim werkt mee aan jouw gezonde levensstijl! Ontdek 10 onmisbare tips die elke zwemmer moet weten.</p>
        <p><a href="#" class="btn btn-primary btn-block" role="button">Check onze tips &rarr;</a></p>
      </div>
    </div>  
  </div>
  <div class="col-sm-4">
    <div class="thumbnail text-center">
      <span class="fa-stack fa-5x">
        <i class="fa fa-circle fa-stack-2x text-muted"></i>
        <i class="fa fa-calendar fa-stack-1x fa-inverse"></i>
      </span>
      <div class="caption">
        <h3>Zwemschema's</h3>
        <p>Zwemmen is goed voor je conditie en humeur. Maar hoe begin je er aan? Met een zwemschema op jouw maat!</p>
        <p><a href="#" class="btn btn-primary btn-block" role="button">Zelf aan de slag &rarr;</a></p>
      </div>
    </div>  
  </div>
  <div class="col-sm-4">
    <div class="thumbnail text-center">
      <span class="fa-stack fa-5x">
        <i class="fa fa-circle fa-stack-2x text-muted"></i>
        <i class="fa fa-info fa-stack-1x fa-inverse"></i>
      </span>
      <div class="caption">
        <h3>Voor lesgevers</h3>
        <p>Organiseer je zelf lessenreeksen en wil je jouw aanbod op onze site publiceren? Of heb je andere vragen?</p>
        <p><a href="#" class="btn btn-primary btn-block" role="button">Meer info &rarr;</a></p>
      </div>
    </div>  
  </div>
</div>